name: BitReport
version: 0.0.1
main: bitlegend.bitreport.BitReport
commands:
    report:
        description: Reports an issue to the server moderation team
        usage: /report <problem>
    rclaim:
        description: Indicates that you have claimed a ticket
        usage: /rclaim <ticket id>
    rlist:
        description: Lists open tickets, their UID and some of their data
        usage: /rlist
    rinfo:
        description: Retrieves and displays information on a particular ticket
        usage: /rinfo <ticket id>
    resolve:
        description: Resolves an open ticket that YOU have claimed
        usage: /resolve <ticket id> <notes>
    rtp:
        description: Used to teleport to the location a report was filed
        usage: /rtp <ticket id> [override]
    rnext:
        description: Used to retrieve the /rinfo of the next available ticket
        usage: /rnext
permissions:
    bitreport.*:
        description: Gives access to all BitReport features
        children:
            bitreport.claim: true
            bitreport.report: true
            bitreport.info: true
            bitreport.list: true
            bitreport.resolve: true
            bitreport.tp: true
            bitreport.tpoverride: true
            bitreport.next: true
    bitreport.claim:
        description: Allows you to claim reported tickets
        default: op
    bitreport.report:
        description: Allows you to report issues to the server moderation team
        default: op
    bitreport.list:
        description: Allows you to use the rlist command
        default: op
    bitreport.info:
        description: Allows you to view information on a specific ticket
        default: op
    bitreport.resolve:
        description: Allows you to use the resolve command to resolve claimed tickets
        default: op
    bitreport.tp:
        description: Allows you to use the rtp command
        default: op
    bitreport.tpoverride:
        description: Allows you to override the default setting and teleport to a resolved ticket location
        default: op
    bitreport.next:
        description: Allows access to the rnext command
        default: op